# Tarea 3 - Inteligencia artificial

'/home/ubuntu/inteligencia_artificial/Tareas/Tarea 3'

## Item 1
Importo dataset (10 puntos)
Fuente: https://www.kaggle.com/datasets/ayessa/salary-prediction-classification

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
dataset = pd.read_csv("./dataset/train22k.csv")
print(dataset.head())
dataset.shape

   age          workclass  fnlwgt   education  education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  salary  
0          2174             0              40   United-States   <=50

(21999, 15)

## Item 2
Entrene el algoritmo KNN sobre los datos seleccionados y aplique predicciones con algún (sub)conjunto DISJUNTO de prueba. Adicionalmente, utilice 3 métricas (a su elección) de error y compárelas entre sí. (15 ptos)

In [53]:
from sklearn.neighbors import KNeighborsClassifier
""" el siguiente es para asociar strings a numeros """
from sklearn.preprocessing import LabelEncoder


#print(type(dataset.iloc[0,1]))
#print(isinstance(dataset.iloc[0,1], str))
#print(dataset.head())
""" Declaro el encoder de string a numeros """
encoder = LabelEncoder()

""" For para iterar el dataset """
for i in range(15):
     """  
     En realidad el dataset es un dataframe de pandas, este tiene propiedades para
     acceder a él. 'iloc' sirve para acceder a él como una matriz con indices
     de fila y columna [x,y].

     Con isisntance puedo ver si la primera fila de datos en cada columna es un string,
     ya que en estos casos debo aplicar la conversion a números """
     if isinstance(dataset.iloc[0,i], str):
          #print(dataset.columns[i], dataset.iloc[0,i])
          #print("type column: ", type(dataset.columns[i])," column:", dataset.columns[i])
          #dataset[dataset.columns[i]] = encoder.fit_transform(dataset.columns[i])
          """
          Con dataset.columns[i] obtengo el nombre de la columna,
          luego convierto esa columna completa en números """
          string = dataset.columns[i]
          dataset[string] = encoder.fit_transform(dataset[string])

#print(dataset.head())
#print(dataset)
#encoder.classes_

def column_string_to_int(columnas, dataset_validation):
     for i in range(columnas):
          if isinstance(dataset_validation.iloc[0,i], str):
               string = dataset_validation.columns[i]
               dataset_validation[string] = encoder.fit_transform(dataset_validation[string])



def entrenar_contar_aciertos(dataset, vecinos):

     x = dataset.iloc[:, :14].values

     y = dataset['salary'].values

     knn = KNeighborsClassifier(n_neighbors=vecinos)

     knn.fit(x, y)
     #Realizo una predicción

     dataset_validation = pd.read_csv("./dataset/validation.csv")
     column_string_to_int(15, dataset_validation)

     x_validation = dataset_validation.iloc[:, :14].values
     y_validation = dataset_validation['salary'].values

     """ Los datos de salario <=50k son 0 y los >50 son 1 """

     """ for i in range(20): 
          if(knn.predict(x_validation[i].reshape(1,-1))[0] == 1):
               print(">50")
          else:
               print("<=50k") """
          #print(knn.predict(x_validation[i].reshape(1,-1))[0])
     prediccion_correcta = []

     for i in range(len(x_validation)): 
          resultado = knn.predict(x_validation[i].reshape(1,-1))[0]
          if resultado == y_validation[i]:
               prediccion_correcta.append(resultado)
          
     #print(  (len(prediccion_correcta)/len(y_validation))*100, "% de presición"  )  
     return (len(prediccion_correcta)/len(y_validation))*100

def buscar_n_optimo(dataset, vecinos_a_probar):
     actual = 0
     i_actual = 0
     for i in range(vecinos_a_probar):
          nuevo = entrenar(dataset, i+1)
          if actual < nuevo:
               actual = nuevo
               i_actual = i+1
               print("i: ", i_actual, " n_vecinos: ", actual )
     print("Cantidad de vecinos con mayor precision: ")
     print("i: ", i_actual, " n_vecinos: ", actual )



x = dataset.iloc[:, :14].values

y = dataset['salary'].values

knn = KNeighborsClassifier(n_neighbors=17)

knn.fit(x, y)
#Realizo una predicción

dataset_validation = pd.read_csv("./dataset/validation.csv")
column_string_to_int(15, dataset_validation)

x_validation = dataset_validation.iloc[:, :14].values
y_validation = dataset_validation['salary'].values

#knn.predict(x_validation[1].reshape(1,-1))[0]

y_pred = knn.predict(x)

score_train = knn.score(x,y)
score_validation = knn.score(x_validation,y_validation)
print("Score_train: ", score_train)
print("score_validation: ", score_validation)

from sklearn import metrics

print("accuracy_score:", metrics.accuracy_score(y, y_pred))

print("hamming_loss:", metrics.hamming_loss(y, y_pred))
print("jaccard_score:", metrics.jaccard_score(y, y_pred))

from sklearn.mixture import GaussianMixture
gm = GaussianMixture(n_components=4, random_state=123).fit(x)
#gm.means_
#c = gm.predict(x)

print(gm.predict(x))
print(gm.predict(x_validation))
print(gm.score(x))
print(gm.weights_)

Score_train:  0.805945724805673
score_validation:  0.7954932777882977
accuracy_score: 0.805945724805673
hamming_loss: 0.19405427519432702
jaccard_score: 0.2177020340846619
[1 3 3 ... 3 3 1]
[3 0 3 ... 3 3 0]
-28.94735451565134
[0.01609181 0.07073507 0.04250194 0.87067118]


## Item 3
Entrene el algoritmo de Regresión Lineal ahora con los mismos datos seleccionados, aplicando también predicciones sobre el mismo (sub)conjunto DISJUNTO de prueba de la parte anterior. Elija alguna métrica de error de entre las tres de la parte anterior y compare los errores, dando una explicación de qué sucede. (15 ptos)

: 

## Item 4
Tome su mismo dataset y entrene dos algoritmos de clasificación: Gaussian Mixture Model y DBSCAN. Evalúe estos algoritmos sobre el mismo (sub)conjunto DISJUNTO de las partes 2 y 3. Analice la diferencia en los resultados entre los algoritmos (10 ptos). Asimismo, indique y aporte evidencia en la diferencia fundamental (clustering vs. estimación de densidad) que existe entre ambos algoritmos (10 ptos).

: 